"""Unit tests for stag.embedded.export_centroids.

Covers:
  * QFormat scale / range / sign behaviour.
  * encode_q_format / decode_q_format round-trip + clipping.
  * verify_round_trip: tight Q-format passes, very-loose Q-format fails.
  * centroids_to_c_header writes a structurally valid header file
    (provenance comment, expected macros, array declarations, no
    trailing parser errors).
"""

from __future__ import annotations

import re
from pathlib import Path

import numpy as np
import pytest

from stag.embedded.export_centroids import (
    QFormat,
    centroids_to_c_header,
    decode_q_format,
    encode_q_format,
    verify_round_trip,
)


class TestQFormat:
    def test_q412_scale(self):
        q = QFormat(int_bits=4, frac_bits=12)
        assert q.scale == 4096
        assert q.total_bits == 16
        assert q.max_signed == 32767
        assert q.min_signed == -32768
        lo, hi = q.range_float
        assert lo == pytest.approx(-8.0)
        assert hi == pytest.approx(8.0 - 1.0 / 4096)

    def test_q015_inverse_divisor_range(self):
        # Q0.15 — used for the inverse MaxAbs divisors (0 .. 0.125).
        q = QFormat(int_bits=1, frac_bits=15)
        assert q.scale == 32768
        assert q.range_float[0] == pytest.approx(-1.0)


class TestEncodeDecode:
    def test_round_trip_zero(self):
        q = QFormat(int_bits=4, frac_bits=12)
        assert encode_q_format(np.array([0.0]), q)[0] == 0
        assert decode_q_format(np.array([0]), q)[0] == 0.0

    def test_round_trip_known_value(self):
        q = QFormat(int_bits=4, frac_bits=12)
        # 0.5 → exactly 2048 in Q4.12
        x = np.array([0.5])
        enc = encode_q_format(x, q)
        assert enc[0] == 2048
        assert decode_q_format(enc, q)[0] == 0.5

    def test_round_trip_small_error_within_lsb(self):
        q = QFormat(int_bits=4, frac_bits=12)
        rng = np.random.default_rng(0)
        x = rng.uniform(-1.0, 1.0, size=500)
        recovered = decode_q_format(encode_q_format(x, q), q)
        assert np.abs(x - recovered).max() < 1.0 / 4096

    def test_clips_out_of_range(self):
        q = QFormat(int_bits=4, frac_bits=12)
        x = np.array([100.0, -100.0])
        enc = encode_q_format(x, q)
        assert enc[0] == q.max_signed
        assert enc[1] == q.min_signed

    def test_empty_input(self):
        q = QFormat(int_bits=4, frac_bits=12)
        enc = encode_q_format(np.array([]), q)
        assert enc.shape == (0,)


class TestVerifyRoundTrip:
    def test_q412_passes_within_tolerance(self):
        rng = np.random.default_rng(0)
        centroids = rng.uniform(-0.6, 0.6, size=(8, 6))
        q = QFormat(int_bits=4, frac_bits=12)
        centroids_q = encode_q_format(centroids, q)
        result = verify_round_trip(centroids, centroids_q, q,
                                   n_test=5_000, tolerance=0.01)
        assert result["passed"]
        assert result["mismatch_fraction"] < 0.01
        assert result["max_abs_quant_error"] < 1.0 / 4096

    def test_loose_q_increases_mismatch(self):
        # Q4.4 = only 4 fractional bits → 1/16 resolution.  Centroids
        # that differ by ~0.05 will sometimes collapse to the same
        # quantised value.
        rng = np.random.default_rng(0)
        centroids = rng.uniform(-0.5, 0.5, size=(8, 6))
        q = QFormat(int_bits=12, frac_bits=4)
        result = verify_round_trip(
            centroids, encode_q_format(centroids, q),
            q, n_test=5_000, tolerance=1.0,  # so 'passed' is True
        )
        # Q4.4 has step 1/16 → max abs encoding error is bounded by
        # 0.5 * 1/16 = 1/32 ≈ 0.03125 (rounding).  Verify the loss is
        # both measurable (> 1/100) and within the theoretical bound.
        assert 1.0 / 100 < result["max_abs_quant_error"] <= 1.0 / 32
        assert result["mismatch_fraction"] > 0.0


class TestHeaderEmission:
    def test_emits_valid_header(self, tmp_path: Path):
        rng = np.random.default_rng(0)
        centroids = rng.uniform(-0.5, 0.5, size=(8, 6))
        divisors = np.full(6, 7.99)
        out = tmp_path / "centroids.h"

        result = centroids_to_c_header(centroids, divisors, out)

        assert out.is_file()
        text = out.read_text()
        # Provenance block
        assert text.startswith("/* Auto-generated by")
        # Header guard
        assert "#ifndef STAG_CENTROIDS_H" in text
        assert "#endif  /* STAG_CENTROIDS_H */" in text.strip().rsplit("\n", 1)[-1] \
            or text.rstrip().endswith("#endif  /* STAG_CENTROIDS_H */")
        # Required macros
        assert "#define STAG_K_CLUSTERS   8" in text
        assert "#define STAG_N_FEATURES   6" in text
        assert "#define STAG_Q_FRAC_BITS  12" in text
        assert "#define STAG_Q_SCALE      4096" in text
        # Both arrays present
        assert "static const int16_t stag_centroids_q[8][6] PROGMEM" in text
        assert "static const float stag_centroids_f[8][6]" in text
        assert "static const int16_t stag_inv_maxabs_q[6] PROGMEM" in text
        assert "static const float stag_inv_maxabs_f[6]" in text
        # AVR PROGMEM shim
        assert "#ifdef __AVR__" in text
        # Verification metadata in comment
        assert "Round-trip verification" in text
        # Verification dict returned correctly
        assert result["passed"]

    def test_rejects_out_of_range_centroids(self, tmp_path: Path):
        centroids = np.array([[10.0, 0, 0, 0, 0, 0]])  # > Q4.12 range
        divisors = np.full(6, 1.0)
        with pytest.raises(ValueError, match="outside Q"):
            centroids_to_c_header(centroids, divisors, tmp_path / "fail.h")

    def test_rejects_wrong_divisor_shape(self, tmp_path: Path):
        centroids = np.zeros((8, 6))
        divisors = np.full(4, 1.0)  # wrong shape
        with pytest.raises(ValueError, match="maxabs_divisors must have shape"):
            centroids_to_c_header(centroids, divisors, tmp_path / "fail.h")

    def test_provenance_block(self, tmp_path: Path):
        centroids = np.zeros((8, 6))
        divisors = np.full(6, 1.0)
        out = tmp_path / "centroids.h"
        centroids_to_c_header(
            centroids, divisors, out,
            source_files={"centroids": Path("/some/path/centroids.npy")},
        )
        text = out.read_text()
        assert "centroids: /some/path/centroids.npy" in text
